FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    git unzip libicu-dev libzip-dev zip zlib1g-dev \
    && docker-php-ext-install intl pdo pdo_mysql zip opcache

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

# Nur composer.json zuerst kopieren (Cache)
COPY composer.json composer.lock ./
RUN composer install --no-interaction --prefer-dist

COPY . .

RUN chown -R www-data:www-data /var/www/html

CMD ["php-fpm"]