name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken
      - uses: actions/checkout@v4

      # Node.js einrichten
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Abhängigkeiten installieren
      - name: Install dependencies
        run: npm install

      # Linting (optional, falls du eslint nutzt)
      # - name: Run lint
      #   run: npm run lint

      # Build ausführen
      - name: Build project
        run: npm run build

      # Optional: Preview starten (nicht nötig für CI, nur zum Testen)
      # - name: Preview project
      #   run: npm run preview
